# permissions for end users to edit githubsecretengineroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githubsecretenginerole-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - githubsecretengineroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - githubsecretengineroles/status
  verbs:
  - get
