# permissions for end users to edit githubsecretengineconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githubsecretengineconfig-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - githubsecretengineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - githubsecretengineconfigs/status
  verbs:
  - get
