# permissions for end users to view githubsecretengineroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githubsecretenginerole-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - githubsecretengineroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - githubsecretengineroles/status
  verbs:
  - get
