# permissions for end users to view githubsecretengineconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githubsecretengineconfig-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - githubsecretengineconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - githubsecretengineconfigs/status
  verbs:
  - get
