# permissions for end users to edit ldapauthenginegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ldapauthenginegroup-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - ldapauthenginegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - ldapauthenginegroups/status
  verbs:
  - get
