# permissions for end users to edit ldapauthengineconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ldapauthengineconfig-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - ldapauthengineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - ldapauthengineconfigs/status
  verbs:
  - get
