# permissions for end users to edit pkisecretengineroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pkisecretenginerole-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - pkisecretengineroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - pkisecretengineroles/status
  verbs:
  - get
