# permissions for end users to edit pkisecretengineconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pkisecretengineconfig-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - pkisecretengineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - pkisecretengineconfigs/status
  verbs:
  - get
