# permissions for end users to view pkisecretengineroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pkisecretenginerole-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - pkisecretengineroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - pkisecretengineroles/status
  verbs:
  - get
