# permissions for end users to edit quaysecretengineroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quaysecretenginerole-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - quaysecretengineroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - quaysecretengineroles/status
  verbs:
  - get
