# permissions for end users to edit quaysecretenginestaticroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quaysecretenginestaticrole-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - quaysecretenginestaticroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - quaysecretenginestaticroles/status
  verbs:
  - get
