# permissions for end users to edit quaysecretengineconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quaysecretengineconfig-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - quaysecretengineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - quaysecretengineconfigs/status
  verbs:
  - get
