# permissions for end users to view quaysecretengineconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quaysecretengineconfig-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - quaysecretengineconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - quaysecretengineconfigs/status
  verbs:
  - get
