# permissions for end users to view quaysecretenginestaticroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quaysecretenginestaticrole-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - quaysecretenginestaticroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - quaysecretenginestaticroles/status
  verbs:
  - get
