# permissions for end users to view vaultsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultsecret-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - vaultsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - vaultsecrets/status
  verbs:
  - get
