apiVersion: redhatcop.redhat.io/v1alpha1
kind: PKISecretEngineRole
metadata:
  name: pkisecretenginerole-sample
spec:
  authentication: 
    path: kubernetes
    role: policy-admin
  path: test-vault-config-operator/pki
  allowedDomains: 
   - internal.io
   - pki-vault-demo.svc
   - example.com
  allowSubdomains: true
  allowedOtherSans: "*"
  allowGlobDomains: true
  allowedURISans: 
  - "*-pki-vault-demo.apps.example.com"
  maxTTL: "8760h"
